name = "star"
version = "1.0.0"
target = "erlang"
description = "Gleam bindings to create, extract, and list tar archives."
licences = ["Apache-2.0"]
repository = { type = "github", user = "jtdowney", repo = "star" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev_dependencies]
qcheck = ">= 1.0.4 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
unitest = ">= 1.5.0 and < 2.0.0"
